sudo: false

addons:
  apt:
    packages:
    - libjpeg-turbo8
    - libjpeg-turbo8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - liblcms2-2
    - liblcms2-dev
    - liblcms-utils
    - libtiff4-dev
    - libwebp-dev

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  allow_failures:
    - python: 3.4
    - python: 3.5
    - python: 3.6

install:
 - pip install -r requirements_test.txt

script:
  - "flake8 --select=F --ignore=F841"
  - "coverage run --module py.test --verbose tests/*.py"
  - "coverage report"

notifications:
  email:
    recipients: "jpstroop@gmail.com"
    on_success: "always"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
