dist: xenial

addons:
  apt:
    packages:
    - libjpeg-turbo8
    - libjpeg-turbo8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - liblcms2-2
    - liblcms2-dev
    - liblcms2-utils
    - libopenjp2-tools
    - libtiff5-dev
    - libwebp-dev

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

jobs:
  allow_failures:
  - python: 3.8

install:
 - pip install -r requirements_test.txt

script:
  - "flake8 --select=F --ignore=F841"
  - "coverage run --module py.test --verbose tests/*.py"
  - "coverage report"

notifications:
  email:
    recipients: "jpstroop@gmail.com"
    on_success: "always"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"

